<?php

namespace Housecare\CalendarBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarElementRepository extends EntityRepository {

   public function findAllCalendarElement() {
      $qb = $this->createQueryBuilder('c')
              ->leftJoin('j.calendarElement', 'c')
              ->addSelect('c');

      return $qb->getQuery()->getResult();
   }
   
   

}
