parameters:
#    housecare_costumers.example.class: Housecare\CostumersBundle\Example

services:
#    housecare_costumers.example:
#        class: %housecare_costumers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
   housecare.CountryManager:
      class: Housecare\CostumersBundle\Country\CountryManager
