<?php

namespace Housecare\CostumersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CostumersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostumersRepository extends EntityRepository
{
}
