<?php

namespace Housecare\JobBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Housecare\JobBundle\Entity\Job;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository {

   public function findAllCalendarElement() {

   }
   
   public function findAllByJobs(){
      $qb = $this->createQueryBuilder('j');

      $qb->leftJoin('j.calendarElement', 'c')
              ->addSelect('c')
              ->where($qb->expr()->isNotNull('j.calendarElement'));


      $owners = $qb->getQuery()->getResult();
      
      return $this->getElementsCalendarByJob($owners);
   }
   
   public function getElementsCalendarByJob($owners){
      $list = array();
      foreach ($owners as $owner) {
         $list[] = $this->getCalendarElementByJob($owner);
      }
      return $list;
   }
   
   public function getCalendarElementByJob(Job $owner){
      /* @var $owner Job */
      $owner->getCalendarElement()->setOwner($owner->getWorker());
      return $owner->getCalendarElement()->setDelegate($owner);
   }

}
